# Copyright (c) 2021 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Ubuntu Builds

on:
  push:
    branches: [ main, testing-ci, v4.1 ]
    paths:
      - ".github/workflows/*.yml"
      - "external/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
  pull_request:
    branches: [ main, testing-ci, v4.1 ]
    paths:
      - ".github/workflows/*.yml"
      - "external/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image:
          - conanio/gcc7-ubuntu16.04:1.41.0
          - conanio/gcc11-ubuntu16.04:1.41.0
          - conanio/clang60:latest
          - conanio/clang13-ubuntu16.04:1.41.0
        config:
          - build_type: Release
          - build_type: Debug

    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
      options: "--user=root -v ${{github.workspace}}:/workspace"
    env:
      CONAN_USER_HOME: "/workspace"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install unit test dependencies
        run: pip3 install scipy

      - name: Collect compiler information
        id: compiler-info
        run: |
          compiler_name="$(basename "$(readlink -f "$(which cc)")" | grep -o "gcc\|clang")"
          compiler_ver="$(cc -dumpversion)"
          compiler_id="${compiler_name}-${compiler_ver}"
          
          echo "::set-output name=NAME::$compiler_name"
          echo "::set-output name=VERSION::$compiler_ver"
          echo "::set-output name=VERSION_MAJOR::$(echo $compiler_ver | grep -oP '^\d+')"
          echo "::set-output name=ID::$compiler_id"

      - name: Generate cache key
        id: conan_cache_key
        run: |
          host_os="host-${{runner.os}}"
          compiler_id="${{ steps.compiler-info.outputs.ID }}"
          build_type="${{matrix.config.build_type}}"
          hash="${{hashFiles('conanfile.py')}}"

          echo "::set-output name=string::$host_os-$compiler_id-$build_type-$hash"

      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          key: conan-${{ steps.conan_cache_key.outputs.string }}
          path: ${{ env.CONAN_USER_HOME }}/.conan/data

      - name: Clean up Conan
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs

      - name: Create build directories
        working-directory: /workspace
        run: mkdir build build-asan build-ubsan

      - name: Configure project
        working-directory: /workspace/build
        env:
          CONAN_V2_MODE: "1"
        run: |
          set -x
          
          waserr='OFF'
          wlto='OFF'

          if [[ ${{ steps.compiler-info.outputs.NAME }} == gcc ]] && \
             [[ ${{ steps.compiler-info.outputs.VERSION_MAJOR }} -ge 9 ]] ; then
            waserr='ON'
            wlto='ON'
          fi
          
          if [[ ${{ steps.compiler-info.outputs.NAME }} == clang ]] && \
             [[ ${{ steps.compiler-info.outputs.VERSION_MAJOR }} -ge 10 ]] ; then
            waserr='ON'
            wlto='ON'
          fi
          
          cmake -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} \
                -DENABLE_IPO=$wlto                               \
                -DENABLE_TESTING=ON                              \
                -DWARNINGS_AS_ERRORS=$waserr                     \
                /workspace

      - name: Build project
        working-directory: /workspace/build
        run: cmake --build . -j $(nproc)

      - name: Test project
        working-directory: /workspace/build
        run: |
          ctest --test-dir /workspace/build \
                --schedule-random           \
                --output-on-failure         \
                --no-tests=error            \
                -j $(nproc)

      - name: Configure project - ASAN
        working-directory: /workspace/build-asan
        if: >
          matrix.config.build_type == 'Debug' &&
             (contains(steps.compiler-info.outputs.ID, 'gcc-11') ||
             contains(steps.compiler-info.outputs.ID, 'clang-13'))
        env:
          CONAN_V2_MODE: "1"
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug      \
                -DENABLE_SANITIZER_ADDRESS=ON \
                -DENABLE_TESTING=ON           \
                -DWARNINGS_AS_ERRORS=ON       \
                /workspace

      - name: Build project - ASAN
        working-directory: /workspace/build-asan
        if: >
          matrix.config.build_type == 'Debug' &&
             (contains(steps.compiler-info.outputs.ID, 'gcc-11') ||
              contains(steps.compiler-info.outputs.ID, 'clang-13'))
        run: cmake --build . -j $(nproc)

      - name: Test project - ASAN
        working-directory: /workspace/build-asan
        if: >
          matrix.config.build_type == 'Debug' &&
             (contains(steps.compiler-info.outputs.ID, 'gcc-11') ||
              contains(steps.compiler-info.outputs.ID, 'clang-13'))
        run: |
          ctest --test-dir /workspace/build-asan \
                --schedule-random                \
                --output-on-failure              \
                --no-tests=error                 \
                -j $(nproc)

      - name: Configure project - UBSAN
        working-directory: /workspace/build-ubsan
        if: >
          matrix.config.build_type == 'Debug' &&
             (contains(steps.compiler-info.outputs.ID, 'gcc-11') ||
              contains(steps.compiler-info.outputs.ID, 'clang-13'))
        env:
          CONAN_V2_MODE: "1"
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug                 \
                -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON \
                -DENABLE_TESTING=ON                      \
                -DWARNINGS_AS_ERRORS=ON                  \
                /workspace

      - name: Build project - UBSAN
        working-directory: /workspace/build-ubsan
        if: >
          matrix.config.build_type == 'Debug' &&
             (contains(steps.compiler-info.outputs.ID, 'gcc-11') ||
              contains(steps.compiler-info.outputs.ID, 'clang-13'))
        run: cmake --build . -j $(nproc)

      - name: Test project - UBSAN
        working-directory: /workspace/build-ubsan
        if: >
          matrix.config.build_type == 'Debug' &&
             (contains(steps.compiler-info.outputs.ID, 'gcc-11') ||
              contains(steps.compiler-info.outputs.ID, 'clang-13'))
        run: |
          ctest --test-dir /workspace/build-ubsan \
                --schedule-random                 \
                --output-on-failure               \
                --no-tests=error                  \
                -j $(nproc)
